### ISSUE TITLE
which version of java required to use this extension ...giving error

### ISSUE THREAD

**Issue by balook** [Leoid/Burp2Slack#1]
giviing error while loading extension ...asking later versiono of java

**Comment by balook** [comment]
my burp version 2020.7

**Comment by balook** [comment]
im using java version \openjdk-12.0.2

**Comment by Leoid** [comment]
Upgrading to 14.0.1 will fix the issue.

**Comment by Leoid** [comment]
The required JDK now is 11 instead of 14.0.1.
